# Generated by Django 4.1.4 on 2022-12-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_year', models.FloatField()),
                ('zodiac_sign', models.CharField(max_length=50)),
                ('is_adult', models.BooleanField()),
            ],
        ),
    ]
